const { Router } = require("express");
const router = Router();
const { Address } = require("../db");
const axios = require("axios");

let listacomuna = [
  {
    provincia: "Buenos Aires",
    comuna:
      "Comuna 1-Retiro,San Nicolás,Puerto Madero, San Telmo,Monserrat y Constitución",
  },
  { provincia: "Buenos Aires", comuna: "Comuna 2-Recoleta" },
  { provincia: "Buenos Aires", comuna: "Comuna 3-San Cristóbal y Balvanera" },
  {
    provincia: "Buenos Aires",
    comuna: "Comuna 4-Boca, Barracas, Parque Patricios y Nueva Pompeya",
  },
  { provincia: "Buenos Aires", comuna: "Comuna 5-Almagro y Boedo" },
  { provincia: "Buenos Aires", comuna: "Comuna 6-Caballito" },
  { provincia: "Buenos Aires", comuna: "Comuna 7-Flores y Parque Chacabuco" },
  {
    provincia: "Buenos Aires",
    comuna: "Comuna 8-Villa Soldati, Villa Riachuelo y Villa Lugano",
  },
  {
    provincia: "Buenos Aires",
    comuna: "Comuna 9-Parque Avellaneda, Liniers y Mataderos",
  },
  {
    provincia: "Buenos Aires",
    comuna:
      "Comuna 10-Villa Real, Monte Castro, Versalles, Floresta, Vélez Sársfield y Villa Luro",
  },
  {
    provincia: "Buenos Aires",
    comuna:
      "Comuna 11-Villa Gral. Mitre, Villa Devoto, Villa del Parque y Villa Santa Rita",
  },
  {
    provincia: "Buenos Aires",
    comuna: "Comuna 12-Coghlan, Saavedra, Villa Urquiza y Villa Pueyrredón",
  },
  {
    provincia: "Buenos Aires",
    comuna: "Comuna 13-Belgrano, Núñez y Colegiales",
  },
  { provincia: "Buenos Aires", comuna: "Comuna 14-Palermo" },
  {
    provincia: "Buenos Aires",
    comuna:
      "Comuna 15-Chacarita, Villa Crespo, Paternal, Villa Ortúzar, Agronomía y Parque Chas",
  },

  { provincia: "Entre Ríos", comuna: "Aldea Asunción" },
  { provincia: "Entre Ríos", comuna: "Aldea Protestante" },
  { provincia: "Entre Ríos", comuna: "Aldea San Juan" },
  { provincia: "Entre Ríos", comuna: "Aldea Santa María" },
  { provincia: "Entre Ríos", comuna: "Aldea Santa Rosa" },
  { provincia: "Entre Ríos", comuna: "Aldea Spatzenkutter" },
  { provincia: "Entre Ríos", comuna: "Arroyo Barú" },
  { provincia: "Entre Ríos", comuna: "Arroyo Corralito" },
  { provincia: "Entre Ríos", comuna: "Arroyo del Medio El Gramiyal" },
  { provincia: "Entre Ríos", comuna: "Chañar" },
  { provincia: "Entre Ríos", comuna: "Colonia Avigdor" },
  { provincia: "Entre Ríos", comuna: "Colonia Ensayo" },
  { provincia: "Entre Ríos", comuna: "Colonia Roca (Colonia General Roca)" },
  { provincia: "Entre Ríos", comuna: "Curtiembre" },
  { provincia: "Entre Ríos", comuna: "Distrito Sexto Costa de Nogoyá" },
  { provincia: "Entre Ríos", comuna: "Eigenfeld Merou" },
  { provincia: "Entre Ríos", comuna: "El Cimarrón" },
  { provincia: "Entre Ríos", comuna: "El Palenque" },
  {
    provincia: "Entre Ríos",
    comuna: "El Solar, San Carlos y Colonia Bertozzi28",
  },
  { provincia: "Entre Ríos", comuna: "Estación Raíces" },
  { provincia: "Entre Ríos", comuna: "Estación Yeruá" },
  { provincia: "Entre Ríos", comuna: "Estación Yuquerí" },
  { provincia: "Entre Ríos", comuna: "General Racedo" },
  { provincia: "Entre Ríos", comuna: "Gobernador Sola" },
  { provincia: "Entre Ríos", comuna: "Gualeguaycito" },
  { provincia: "Entre Ríos", comuna: "Irazusta" },
  { provincia: "Entre Ríos", comuna: "Jubileo" },
  { provincia: "Entre Ríos", comuna: "La Clarita" },
  { provincia: "Entre Ríos", comuna: "La Picada" },
  { provincia: "Entre Ríos", comuna: "La Verbena" },
  { provincia: "Entre Ríos", comuna: "Las Cuevas" },
  { provincia: "Entre Ríos", comuna: "Las Moscas" },
  { provincia: "Entre Ríos", comuna: "Las Tunas (Paraje Las Tunas)" },
  { provincia: "Entre Ríos", comuna: "Lucas Norte" },
  { provincia: "Entre Ríos", comuna: "Médanos" },
  { provincia: "Entre Ríos", comuna: "Nueva Escocia" },
  { provincia: "Entre Ríos", comuna: "Nueva Vizcaya" },
  { provincia: "Entre Ríos", comuna: "Paso de la Laguna" },
  { provincia: "Entre Ríos", comuna: "Pueblo General Alvear" },
  { provincia: "Entre Ríos", comuna: "Rincón de Nogoyá" },
  { provincia: "Entre Ríos", comuna: "Rincón del Doll" },
  { provincia: "Entre Ríos", comuna: "San Cipriano" },
  { provincia: "Entre Ríos", comuna: "San Marcial" },
  { provincia: "Entre Ríos", comuna: "San Pedro" },
  { provincia: "Entre Ríos", comuna: "San Víctor" },
  { provincia: "Entre Ríos", comuna: "Sauce Montrull" },
  { provincia: "Entre Ríos", comuna: "Sosa" },
  { provincia: "Entre Ríos", comuna: "Tala" },
  { provincia: "Santa Fe", comuna: "Aarón Castellanos" },
  { provincia: "Santa Fe", comuna: "Acebal" },
  { provincia: "Santa Fe", comuna: "Aguará Grande" },
  { provincia: "Santa Fe", comuna: "Albarellos" },
  { provincia: "Santa Fe", comuna: "Alcorta" },
  { provincia: "Santa Fe", comuna: "Aldao" },
  { provincia: "Santa Fe", comuna: "Alejandra" },
  { provincia: "Santa Fe", comuna: "Álvarez" },
  { provincia: "Santa Fe", comuna: "Alvear" },
  { provincia: "Santa Fe", comuna: "Ambrosetti" },
  { provincia: "Santa Fe", comuna: "Amenábar" },
  { provincia: "Santa Fe", comuna: "Angélica" },
  { provincia: "Santa Fe", comuna: "Angeloni" },
  { provincia: "Santa Fe", comuna: "Arequito" },
  { provincia: "Santa Fe", comuna: "Arminda" },
  { provincia: "Santa Fe", comuna: "Arocena" },
  { provincia: "Santa Fe", comuna: "Arroyo Aguiar" },
  { provincia: "Santa Fe", comuna: "Arroyo Ceibal" },
  { provincia: "Santa Fe", comuna: "Arroyo Leyes" },
  { provincia: "Santa Fe", comuna: "Arrufó" },
  { provincia: "Santa Fe", comuna: "Arteaga" },
  { provincia: "Santa Fe", comuna: "Ataliva" },
  { provincia: "Santa Fe", comuna: "Aurelia" },
  { provincia: "Santa Fe", comuna: "Barrancas" },
  { provincia: "Santa Fe", comuna: "Bauer y Sigel" },
  { provincia: "Santa Fe", comuna: "Bella Italia" },
  { provincia: "Santa Fe", comuna: "Berabevú" },
  { provincia: "Santa Fe", comuna: "Berna" },
  { provincia: "Santa Fe", comuna: "Bernardo de Irigoyen" },
  { provincia: "Santa Fe", comuna: "Bigand" },
  { provincia: "Santa Fe", comuna: "Bombal" },
  { provincia: "Santa Fe", comuna: "Bouquet" },
  { provincia: "Santa Fe", comuna: "Bustinza" },
  { provincia: "Santa Fe", comuna: "Cabal" },
  { provincia: "Santa Fe", comuna: "Cacique Ariacaiquín" },
  { provincia: "Santa Fe", comuna: "Cafferata" },
  { provincia: "Santa Fe", comuna: "Campo Andino" },
  { provincia: "Santa Fe", comuna: "Campo Hardy7(Hardy)" },
  { provincia: "Santa Fe", comuna: "Campo Piaggio" },
  { provincia: "Santa Fe", comuna: "Candioti" },
  { provincia: "Santa Fe", comuna: "Cañada del Ucle" },
  { provincia: "Santa Fe", comuna: "Cañada Ombú" },
  { provincia: "Santa Fe", comuna: "Cañada Rica" },
  { provincia: "Santa Fe", comuna: "Cañada Rosquín" },
  { provincia: "Santa Fe", comuna: "Capivara" },
  { provincia: "Santa Fe", comuna: "Carlos Pellegrini" },
  { provincia: "Santa Fe", comuna: "Carmen" },
  { provincia: "Santa Fe", comuna: "Carmen del Sauce" },
  { provincia: "Santa Fe", comuna: "Carreras" },
  { provincia: "Santa Fe", comuna: "Carrizales/ Clarke" },
  { provincia: "Santa Fe", comuna: "Casalegno" },
  { provincia: "Santa Fe", comuna: "Casas" },
  { provincia: "Santa Fe", comuna: "Castelar" },
  { provincia: "Santa Fe", comuna: "Castellanos" },
  { provincia: "Santa Fe", comuna: "Cayastá" },
  { provincia: "Santa Fe", comuna: "Cayastacito" },
  { provincia: "Santa Fe", comuna: "Centeno" },
  { provincia: "Santa Fe", comuna: "Cepeda" },
  { provincia: "Santa Fe", comuna: "Chabás" },
  { provincia: "Santa Fe", comuna: "Chañar Ladeado" },
  { provincia: "Santa Fe", comuna: "Chapuy" },
  { provincia: "Santa Fe", comuna: "Chovet" },
  { provincia: "Santa Fe", comuna: "Christophersen" },
  { provincia: "Santa Fe", comuna: "Classon" },
  { provincia: "Santa Fe", comuna: "Colonia Aldao" },
  { provincia: "Santa Fe", comuna: "Colonia Ana" },
  { provincia: "Santa Fe", comuna: "Colonia Belgrano" },
  { provincia: "Santa Fe", comuna: "Colonia Bicha" },
  { provincia: "Santa Fe", comuna: "Colonia Bigand" },
  { provincia: "Santa Fe", comuna: "Colonia Bossi" },
  { provincia: "Santa Fe", comuna: "Colonia Cavour (Cavour)" },
  { provincia: "Santa Fe", comuna: "Colonia Cello" },
  { provincia: "Santa Fe", comuna: "Colonia Clara" },
  { provincia: "Santa Fe", comuna: "Colonia Dolores" },
  { provincia: "Santa Fe", comuna: "Colonia Dos Rosas y La Legua" },
  { provincia: "Santa Fe", comuna: "Colonia Durán" },
  { provincia: "Santa Fe", comuna: "Colonia Esther (Esther)" },
  { provincia: "Santa Fe", comuna: "Colonia Iturraspe" },
  { provincia: "Santa Fe", comuna: "Colonia Margarita" },
  { provincia: "Santa Fe", comuna: "Colonia Mascías" },
  { provincia: "Santa Fe", comuna: "Colonia Mauá" },
  { provincia: "Santa Fe", comuna: "Colonia Raquel" },
  { provincia: "Santa Fe", comuna: "Colonia Rosa" },
  { provincia: "Santa Fe", comuna: "Colonia San José (San José)" },
  { provincia: "Santa Fe", comuna: "Colonia Teresa8" },
  { provincia: "Santa Fe", comuna: "Constanza" },
  { provincia: "Santa Fe", comuna: "Coronel Arnold" },
  { provincia: "Santa Fe", comuna: "Coronel Bogado" },
  { provincia: "Santa Fe", comuna: "Coronel Fraga" },
  {
    provincia: "Santa Fe",
    comuna: "Coronel Rodolfo S. Domínguez (Coronel Domínguez)",
  },
  { provincia: "Santa Fe", comuna: "Correa" },
  { provincia: "Santa Fe", comuna: "Crispi" },
  { provincia: "Santa Fe", comuna: "Cululú" },
  { provincia: "Santa Fe", comuna: "Curupaity" },
  { provincia: "Santa Fe", comuna: "Desvío Arijón" },
  { provincia: "Santa Fe", comuna: "Díaz" },
  { provincia: "Santa Fe", comuna: "Diego de Alvear" },
  { provincia: "Santa Fe", comuna: "Egusquiza" },
  { provincia: "Santa Fe", comuna: "El Arazá" },
  { provincia: "Santa Fe", comuna: "El Rabón" },
  { provincia: "Santa Fe", comuna: "El Sombrerito" },
  { provincia: "Santa Fe", comuna: "Elisa" },
  { provincia: "Santa Fe", comuna: "Elortondo" },
  { provincia: "Santa Fe", comuna: "Emilia" },
  { provincia: "Santa Fe", comuna: "Empalme San Carlos" },
  { provincia: "Santa Fe", comuna: "Empalme Villa Constitución" },
  { provincia: "Santa Fe", comuna: "Esmeralda" },
  { provincia: "Santa Fe", comuna: "Estación Clucellas" },
  { provincia: "Santa Fe", comuna: "Esteban Rams" },
  { provincia: "Santa Fe", comuna: "Eusebia y Carolina" },
  { provincia: "Santa Fe", comuna: "Eustolia" },
  { provincia: "Santa Fe", comuna: "Felicia" },
  { provincia: "Santa Fe", comuna: "Fidela" },
  { provincia: "Santa Fe", comuna: "Fighiera" },
  { provincia: "Santa Fe", comuna: "Fortín Olmos" },
  { provincia: "Santa Fe", comuna: "Franck" },
  { provincia: "Santa Fe", comuna: "Fuentes" },
  { provincia: "Santa Fe", comuna: "Gaboto" },
  { provincia: "Santa Fe", comuna: "Galisteo" },
  { provincia: "Santa Fe", comuna: "Garabato" },
  { provincia: "Santa Fe", comuna: "Garibaldi" },
  { provincia: "Santa Fe", comuna: "Gato Colorado" },
  { provincia: "Santa Fe", comuna: "General Gelly" },
  { provincia: "Santa Fe", comuna: "General Lagos" },
  { provincia: "Santa Fe", comuna: "Gessler" },
  { provincia: "Santa Fe", comuna: "Gobernador Crespo" },
  { provincia: "Santa Fe", comuna: "Gödeken" },
  { provincia: "Santa Fe", comuna: "Godoy" },
  { provincia: "Santa Fe", comuna: "Golondrina" },
  {
    provincia: "Santa Fe",
    comuna: "Gregoria Pérez de Denis (Los Saladillos)",
  },
  { provincia: "Santa Fe", comuna: "Grutly" },
  { provincia: "Santa Fe", comuna: "Guadalupe Norte" },
  { provincia: "Santa Fe", comuna: "Helvecia" },
  { provincia: "Santa Fe", comuna: "Hersilia" },
  { provincia: "Santa Fe", comuna: "Hipatia" },
  { provincia: "Santa Fe", comuna: "Huanqueros" },
  { provincia: "Santa Fe", comuna: "Hugentobler" },
  { provincia: "Santa Fe", comuna: "Hughes" },
  { provincia: "Santa Fe", comuna: "Humberto Primo" },
  { provincia: "Santa Fe", comuna: "Humboldt" },
  { provincia: "Santa Fe", comuna: "Ibarlucea" },
  { provincia: "Santa Fe", comuna: "Ingeniero Chanourdie" },
  { provincia: "Santa Fe", comuna: "Intiyaco" },
  { provincia: "Santa Fe", comuna: "Ituzaingó" },
  { provincia: "Santa Fe", comuna: "Jacinto L. Arauz" },
  { provincia: "Santa Fe", comuna: "Josefina" },
  { provincia: "Santa Fe", comuna: "Juan Bernabé Molina" },
  { provincia: "Santa Fe", comuna: "Juan de Garay" },
  { provincia: "Santa Fe", comuna: "Juncal" },
  { provincia: "Santa Fe", comuna: "La Brava" },
  { provincia: "Santa Fe", comuna: "La Cabral" },
  { provincia: "Santa Fe", comuna: "La Camila" },
  { provincia: "Santa Fe", comuna: "La Chispa" },
  { provincia: "Santa Fe", comuna: "La Criolla" },
  { provincia: "Santa Fe", comuna: "La Gallareta" },
  { provincia: "Santa Fe", comuna: "La Lucila" },
  { provincia: "Santa Fe", comuna: "La Pelada" },
  { provincia: "Santa Fe", comuna: "La Penca y Caraguatá" },
  { provincia: "Santa Fe", comuna: "La Rubia" },
  { provincia: "Santa Fe", comuna: "La Sarita" },
  { provincia: "Santa Fe", comuna: "La Vanguardia" },
  { provincia: "Santa Fe", comuna: "Labordeboy" },
  { provincia: "Santa Fe", comuna: "Landeta" },
  { provincia: "Santa Fe", comuna: "Lanteri" },
  { provincia: "Santa Fe", comuna: "Larrechea" },
  { provincia: "Santa Fe", comuna: "Las Avispas" },
  { provincia: "Santa Fe", comuna: "Las Bandurrias" },
  { provincia: "Santa Fe", comuna: "Las Garzas" },
  { provincia: "Santa Fe", comuna: "Las Palmeras" },
  { provincia: "Santa Fe", comuna: "Las Petacas" },
  { provincia: "Santa Fe", comuna: "Las Tunas" },
  { provincia: "Santa Fe", comuna: "Lazzarino" },
  { provincia: "Santa Fe", comuna: "Lehmann" },
  { provincia: "Santa Fe", comuna: "Llambi Campbell" },
  { provincia: "Santa Fe", comuna: "Logroño" },
  { provincia: "Santa Fe", comuna: "Loma Alta" },
  { provincia: "Santa Fe", comuna: "López" },
  { provincia: "Santa Fe", comuna: "Los Amores" },
  { provincia: "Santa Fe", comuna: "Los Cardos" },
  { provincia: "Santa Fe", comuna: "Los Laureles" },
  { provincia: "Santa Fe", comuna: "Los Molinos" },
  { provincia: "Santa Fe", comuna: "Los Quirquinchos" },
  { provincia: "Santa Fe", comuna: "Los Tábanos9" },
  { provincia: "Santa Fe", comuna: "Lucio V. López" },
  { provincia: "Santa Fe", comuna: "Luis Palacios" },
  { provincia: "Santa Fe", comuna: "Maciel" },
  { provincia: "Santa Fe", comuna: "Maggiolo" },
  { provincia: "Santa Fe", comuna: "Marcelino Escalada" },
  { provincia: "Santa Fe", comuna: "Margarita" },
  { provincia: "Santa Fe", comuna: "María Juana" },
  { provincia: "Santa Fe", comuna: "María Luisa" },
  { provincia: "Santa Fe", comuna: "María Susana" },
  { provincia: "Santa Fe", comuna: "María Teresa" },
  { provincia: "Santa Fe", comuna: "Matilde" },
  { provincia: "Santa Fe", comuna: "Máximo Paz" },
  { provincia: "Santa Fe", comuna: "Melincué" },
  { provincia: "Santa Fe", comuna: "Miguel Torres" },
  { provincia: "Santa Fe", comuna: "Moisés Ville" },
  { provincia: "Santa Fe", comuna: "Monigotes" },
  { provincia: "Santa Fe", comuna: "Monje" },
  { provincia: "Santa Fe", comuna: "Monte Oscuridad" },
  { provincia: "Santa Fe", comuna: "Monte Vera" },
  { provincia: "Santa Fe", comuna: "Montefiore" },
  { provincia: "Santa Fe", comuna: "Montes de Oca" },
  { provincia: "Santa Fe", comuna: "Murphy" },
  { provincia: "Santa Fe", comuna: "Naré" },
  { provincia: "Santa Fe", comuna: "Nelson" },
  { provincia: "Santa Fe", comuna: "Nicanor Molinas" },
  { provincia: "Santa Fe", comuna: "Nuevo Torino" },
  { provincia: "Santa Fe", comuna: "Ñanducita" },
  { provincia: "Santa Fe", comuna: "Oliveros" },
  { provincia: "Santa Fe", comuna: "Palacios" },
  { provincia: "Santa Fe", comuna: "Pavón" },
  { provincia: "Santa Fe", comuna: "Pavón Arriba" },
  { provincia: "Santa Fe", comuna: "Pedro Gómez Cello" },
  { provincia: "Santa Fe", comuna: "Peyrano" },
  { provincia: "Santa Fe", comuna: "Piamonte" },
  { provincia: "Santa Fe", comuna: "Pilar" },
  { provincia: "Santa Fe", comuna: "Piñero" },
  { provincia: "Santa Fe", comuna: "Plaza Clucellas" },
  { provincia: "Santa Fe", comuna: "Portugalete" },
  { provincia: "Santa Fe", comuna: "Pozo Borrado" },
  { provincia: "Santa Fe", comuna: "Presidente Roca" },
  { provincia: "Santa Fe", comuna: "Progreso" },
  { provincia: "Santa Fe", comuna: "Providencia" },
  { provincia: "Santa Fe", comuna: "Pueblo Andino" },
  { provincia: "Santa Fe", comuna: "Pueblo Irigoyen (Irigoyen)" },
  { provincia: "Santa Fe", comuna: "Pueblo Marini" },
  { provincia: "Santa Fe", comuna: "Pueblo Muñoz" },
  { provincia: "Santa Fe", comuna: "Pueblo Uranga (Uranga)" },
  { provincia: "Santa Fe", comuna: "Pujato" },
  { provincia: "Santa Fe", comuna: "Pujato Norte" },
  { provincia: "Santa Fe", comuna: "Ramayón" },
  { provincia: "Santa Fe", comuna: "Ramona" },
  { provincia: "Santa Fe", comuna: "Ricardone" },
  { provincia: "Santa Fe", comuna: "Rivadavia" },
  { provincia: "Santa Fe", comuna: "Rueda" },
  { provincia: "Santa Fe", comuna: "Sa Pereira" },
  { provincia: "Santa Fe", comuna: "Saguier" },
  { provincia: "Santa Fe", comuna: "Saladero Mariano Cabal" },
  { provincia: "Santa Fe", comuna: "Salto Grande" },
  { provincia: "Santa Fe", comuna: "San Agustín" },
  { provincia: "Santa Fe", comuna: "San Antonio" },
  { provincia: "Santa Fe", comuna: "San Antonio de Obligado" },
  { provincia: "Santa Fe", comuna: "San Bernardo" },
  { provincia: "Santa Fe", comuna: "San Bernardo" },
  { provincia: "Santa Fe", comuna: "San Carlos Norte" },
  { provincia: "Santa Fe", comuna: "San Carlos Sud" },
  { provincia: "Santa Fe", comuna: "San Eduardo" },
  { provincia: "Santa Fe", comuna: "San Eugenio" },
  { provincia: "Santa Fe", comuna: "San Fabián" },
  { provincia: "Santa Fe", comuna: "San Francisco de Santa Fe" },
  { provincia: "Santa Fe", comuna: "San Gregorio" },
  { provincia: "Santa Fe", comuna: "San Jerónimo del Sauce" },
  { provincia: "Santa Fe", comuna: "San Jerónimo Sud" },
  { provincia: "Santa Fe", comuna: "San José de la Esquina" },
  { provincia: "Santa Fe", comuna: "San Mariano" },
  { provincia: "Santa Fe", comuna: "San Martín de las Escobas" },
  { provincia: "Santa Fe", comuna: "San Martín Norte" },
  { provincia: "Santa Fe", comuna: "San Vicente" },
  { provincia: "Santa Fe", comuna: "Sancti Spiritu" },
  { provincia: "Santa Fe", comuna: "Sanford" },
  { provincia: "Santa Fe", comuna: "Santa Clara de Buena Vista" },
  { provincia: "Santa Fe", comuna: "Santa Clara de Saguier" },
  { provincia: "Santa Fe", comuna: "Santa Isabel" },
  { provincia: "Santa Fe", comuna: "Santa Margarita" },
  { provincia: "Santa Fe", comuna: "Santa María Centro" },
  { provincia: "Santa Fe", comuna: "Santa María Norte" },
  { provincia: "Santa Fe", comuna: "Santa Rosa de Calchines" },
  { provincia: "Santa Fe", comuna: "Santa Teresa" },
  { provincia: "Santa Fe", comuna: "Santo Domingo" },
  { provincia: "Santa Fe", comuna: "Santurce" },
  { provincia: "Santa Fe", comuna: "Sargento Cabral" },
  { provincia: "Santa Fe", comuna: "Sarmiento" },
  { provincia: "Santa Fe", comuna: "Sauce Viejo" },
  { provincia: "Santa Fe", comuna: "Serodino" },
  { provincia: "Santa Fe", comuna: "Silva" },
  { provincia: "Santa Fe", comuna: "Soldini" },
  { provincia: "Santa Fe", comuna: "Soledad" },
  { provincia: "Santa Fe", comuna: "Soutomayor" },
  { provincia: "Santa Fe", comuna: "Susana" },
  { provincia: "Santa Fe", comuna: "Tacuarendí" },
  { provincia: "Santa Fe", comuna: "Tacural" },
  { provincia: "Santa Fe", comuna: "Tacurales" },
  { provincia: "Santa Fe", comuna: "Tartagal" },
  { provincia: "Santa Fe", comuna: "Teodelina" },
  { provincia: "Santa Fe", comuna: "Theobald" },
  { provincia: "Santa Fe", comuna: "Timbúes" },
  { provincia: "Santa Fe", comuna: "Toba" },
  { provincia: "Santa Fe", comuna: "Tortugas" },
  { provincia: "Santa Fe", comuna: "Traill" },
  { provincia: "Santa Fe", comuna: "Vera y Pintado" },
  { provincia: "Santa Fe", comuna: "Videla" },
  { provincia: "Santa Fe", comuna: "Vila" },
  { provincia: "Santa Fe", comuna: "Villa Amelia" },
  { provincia: "Santa Fe", comuna: "Villa Ana" },
  { provincia: "Santa Fe", comuna: "Villa Eloísa" },
  { provincia: "Santa Fe", comuna: "Villa Guillermina" },
  { provincia: "Santa Fe", comuna: "Villa Minetti" },
  { provincia: "Santa Fe", comuna: "Villa Mugueta" },
  { provincia: "Santa Fe", comuna: "Villa San José" },
  { provincia: "Santa Fe", comuna: "Villa Saralegui" },
  { provincia: "Santa Fe", comuna: "Villa Trinidad" },
  { provincia: "Santa Fe", comuna: "Villada" },
  { provincia: "Santa Fe", comuna: "Virginia" },
  { provincia: "Santa Fe", comuna: "Wheelwright" },
  { provincia: "Santa Fe", comuna: "Zavalla" },
  { provincia: "Santa Fe", comuna: "Zenón Pereyra" },
];

listacomuna.forEach((item) => {
  if (item.provincia === "Santa Fe") {
    item["valorEntrega"] = 100;
  }

  if (item.provincia === "Entre Ríos") {
    item["valorEntrega"] = 200;
  }

  if (item.provincia === "Buenos Aires") {
    item["valorEntrega"] = 400;
  }
});

router.post("/", async function (req, res) {
  try {
    await Address.bulkCreate(listacomuna);
    res.send("ok");
  } catch (error) {
    console.log(error.message);
  }
});

router.get("/", async function (req, res) {
  /* const { provincia } = req.query; */
  try {
    let comunas = await Address.findAll();
    res.send(comunas);
  } catch (error) {
    console.log(error);
  }
});

module.exports = router;
