const { Router } = require("express");
const productsRouter = require("./products.js");
const colorRouter = require("./color.js");
const categoriesRouter = require("./category.js");
const typesRouter = require("./types.js");
const sizesRouter = require("./size.js");
const filtersRouter = require("./filterAll.js");
const mockRouter = require("./mock.js");
const Payment = require("./payment.js");
const customerRouter = require("./customer.js");
const ordersRouter = require("./orders");
const rankproductRouter = require("./rankproduct");
const direcciones = require("./direcciones");

const router = Router();
router.use("/payment", Payment);
router.use("/products", productsRouter);
router.use("/color", colorRouter);
router.use("/categories", categoriesRouter);
router.use("/types", typesRouter);
router.use("/sizes", sizesRouter);
router.use("/filters", filtersRouter);
router.use("/mock", mockRouter);
router.use("/orders", ordersRouter);
router.use("/customer", customerRouter);
router.use("/rank", rankproductRouter);
router.use("/direcciones", direcciones);
module.exports = router;
