export const GET_PRODUCTS = "GET_PRODUCTS";
export const FILTER_ALL = "FILTER_ALL";
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";
export const ORDER_BY_PRICE = "ORDER_BY_PRICE";
export const ORDER_DETAIL = "ORDER_DETAIL";

export const POST_CUSTOMER = "POST_CUSTOMER";
export const GET_USER_CREDENTIALS = "GET_USER_CREDENTIALS";
export const CUSTOMER_BY_EMAIL = "CUSTOMER_BY_EMAIL";
export const CUSTOMER_ORDERS = "CUSTOMER_ORDERS";
export const GET_ALL_ORDERS = "GET_ALL_ORDERS";
export const DELETE_ORDER = "DELETE_ORDER";
export const UPDATE_STATUS = "UPDATE_STATUS";
export const GET_USERS = "GET_USERS";
export const UPDATE_ADMIN = "UPDATE_ADMIN";
export const DELETE_USER = "DELETE_USER";
