export const GET_PRODUCTS = "GET_PRODUCTS";
export const FILTER_ALL = "FILTER_ALL";
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";
export const ORDER_BY_PRICE = "ORDER_BY_PRICE";
export const ORDER_DETAIL = "ORDER_DETAIL"